version: "3.8"

services:
  # Next.js Frontend
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      ANALYTICS_API_URL: http://analytics:8002
      AUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_URL: https://inflasi.id
      AUTH_TRUST_HOST: "true"

 