apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - priorityclasses.yaml
  - pvc.yaml
  - deployment.yaml
  - deployment-gpu.yaml
  - service.yaml
  - service-gpu.yaml
